(deftheme ample-zen-martin
  "Created 2017-10-07.")

(custom-theme-set-variables
 'ample-zen-martin
 '(ansi-color-names-vector ["#212121" "#CC5542" "#6aaf50" "#7d7c61" "#5180b3" "#DC8CC3" "#9b55c3" "#bdbdb3"]))

(custom-theme-set-faces
 'ample-zen-martin
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#7d7c61" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#baba36" :underline t :weight normal))))
 '(cursor ((t (:foreground "#bdbdb3" :background "#cc8512"))))
 '(escape-glyph ((t (:foreground "#7d7c61" :bold t))))
 '(fringe ((t (:foreground "#bdbdb3" :background "#212121"))))
 '(header-line ((t (:box (:line-width -1 :style released-button) :background "#3b3b3b" :foreground "#7d7c61"))))
 '(highlight ((t (:background "#282828"))))
 '(success ((t (:foreground "#6aaf50" :weight bold))))
 '(warning ((t (:foreground "#fb8512" :weight bold))))
 '(error ((t (:foreground "#AA5542" :weight bold))))
 '(menu ((t (:foreground "#bdbdb3" :background "#212121"))))
 '(minibuffer-prompt ((t (:foreground "#7d7c61"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#c9c9c9" :background "#000000" :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 '(mode-line-buffer-id ((t (:foreground "#cc8512" :weight bold))))
 '(mode-line-inactive ((t (:foreground "#9b9b9b" :background "#3b3b3b" :box nil :weight light))))
 '(region ((t (:background "#3b3b3b"))))
 '(secondary-selection ((t (:background "#0a0a0a"))))
 '(trailing-whitespace ((t (:background "#CC5542"))))
 '(vertical-border ((t (:foreground "#bdbdb3"))))
 '(scroll-bar ((t (:background "#0a0a0a" :foreground "#9b9b9b"))))
 '(compilation-info ((t (:foreground "#6a7550" :underline t))))
 '(compilation-line-number ((t (:foreground "#7d7c61"))))
 '(compilation-mode-line-exit ((t (:foreground "#6a9550" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#CC5542" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#7d7c61" :weight bold))))
 '(match ((t (:background "#3b3b3b" :foreground "#fb8512" :weight bold))))
 '(isearch ((t (:foreground "#baba36" :weight bold :background "#3b3b3b"))))
 '(isearch-fail ((t (:foreground "#bdbdb3" :background "#ff6642"))))
 '(lazy-highlight ((t (:foreground "#baba36" :weight bold :background "#2e2e2e"))))
 '(font-lock-builtin-face ((t (:foreground "#bdbdb3" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#6aaf50"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#6abd50"))))
 '(font-lock-constant-face ((t (:foreground "#6a7550"))))
 '(font-lock-doc-face ((t (:foreground "#6a9550"))))
 '(font-lock-function-name-face ((t (:foreground "#9b55c3"))))
 '(font-lock-keyword-face ((t (:foreground "#7d7c61" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#7d7c61" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#6380b3"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#7d7c61" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#6aaf50" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#CC5542"))))
 '(font-lock-type-face ((t (:foreground "cyan4" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "#fb8512"))))
 '(font-lock-warning-face ((t (:foreground "#baba36" :weight bold))))
 '(c-annotation-face ((t (:inherit font-lock-constant-face))))
 '(flycheck-error ((((supports :underline (:style wave))) (:underline (:style wave :color "#CC5542") :inherit unspecified)) (t (:foreground "#dd5542" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave))) (:underline (:style wave :color "#fb8512") :inherit unspecified)) (t (:foreground "#fb8512" :weight bold :underline t))))
 '(flycheck-fringe-error ((t (:foreground "#dd5542" :weight bold))))
 '(flycheck-fringe-warning ((t (:foreground "#fb8512" :weight bold))))
 '(linum ((t (:foreground "#6a9550" :background "#212121"))))
 '(show-paren-mismatch ((t (:foreground "#ff5542" :background "#212121" :weight bold))))
 '(show-paren-match ((t (:background "#888888" :foreground "#000000" :weight bold))))
 '(whitespace-space ((t (:background "#141414" :foreground "#141414"))))
 '(whitespace-hspace ((t (:background "#141414" :foreground "#141414"))))
 '(whitespace-tab ((t (:background "#dd5542"))))
 '(whitespace-newline ((t (:foreground "#141414"))))
 '(whitespace-trailing ((t (:background "#ff0000"))))
 '(whitespace-line ((t (:foreground "#ff0000" :weight bold))))
 '(whitespace-space-before-tab ((t (:background "#fb8512" :foreground "#fb8512"))))
 '(whitespace-indentation ((t (:background "#7d7c61" :foreground "#CC5542"))))
 '(whitespace-empty ((t (:background "#7d7c61"))))
 '(whitespace-space-after-tab ((t (:background "#7d7c61" :foreground "#CC5542"))))
 '(which-func ((t (:foreground "#6a7550"))))
 '(default ((t (:background "#212121" :foreground "#bdbdb3")))))

(provide-theme 'ample-zen-martin)
